AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Gemfile
    - standard_assert.gemspec

Metrics/LineLength:
  Max: 100

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
